name: Development workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-lateste

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Prepare Backend
        run: npm run prepare-backend

      - name: Prepare Frontend
        run: npm run prepare-react

      - name: Run Tests
        run: npm run test-react
